title: "GUIHUA: FURP Journal Weekly"
description: "The weekly digest of GUIHUA: Frontiers of Urban and Rural Planning (FURP), covering the Editor-in-Chief’s weekly reflections, FURP article highlights, academic conferences, scholar interviews, urban planning news, emerging urban technologies, book recommendations, and FURP Journal Updates."
theme: jekyll-theme-minimal
show_downloads: false
